language: rust
sudo: false
cache: cargo

matrix:
  fast_finish: true

  include:
    - rust: 1.30.0
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test --all
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test --all-features

    - rust: nightly
      name: cargo test (minimal versions)
      script:
        - cargo update -Zminimal-versions
        - cargo test --all
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test --all-features

    - rust: nightly
      name: cargo doc
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps

before_script:
  - set -o errexit

script:
  - cargo test --all
  - cd "${TRAVIS_BUILD_DIR}/test_suite"
  - cargo test --features build_script

notifications:
  email:
    on_success: never
