language: rust
sudo: false
cache: cargo

matrix:
  fast_finish: true

  include:
    # This is the minimum Rust version supported by const_fn.
    # When updating this, the reminder to update the minimum required version in README.md.
    - rust: 1.30.0

    - rust: stable
      script:
        - cargo test
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test --features min_const_fn
    - rust: beta
      script:
        - cargo test
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test --features const_let
    - rust: nightly
      script:
        - cargo test --all --all-features

    - rust: nightly
      name: cargo test (minimal versions)
      script:
        - cargo update -Zminimal-versions
        - cargo test --all --all-features

    - rust: nightly
      name: cargo clippy
      script:
        - if rustup component add clippy-preview;
          then
            cargo clippy --all --all-features -- -Dwarnings;
          else
            echo 'Skipping clippy';
          fi

    - rust: stable
      name: cargo fmt
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

    - rust: nightly
      name: cargo doc
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps

before_script:
  - set -o errexit

script:
  - cargo test --all

notifications:
  email:
    on_success: never
