language: rust
sudo: false
cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true

  include:
    # This is the minimum Rust version supported by const_fn.
    # When updating this, the reminder to update the minimum required version in README.md.
    - rust: 1.31.0

    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test --all --all-features

    - rust: nightly
      name: cargo check (minimal versions)
      script:
        - cargo update -Zminimal-versions
        - cargo check --all --all-features

    - rust: nightly
      name: cargo clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy --all --all-features --tests

    - rust: stable
      name: cargo fmt
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

    - rust: nightly
      name: cargo doc
      script:
        - RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps

env:
  - RUSTFLAGS=-Dwarnings

before_script:
  - set -o errexit

script:
  - cargo check --all

notifications:
  email:
    on_success: never
