jobs:
- job: ${{ parameters.name }}
  displayName: Clippy
  pool:
    vmImage: ubuntu-16.04

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}

    - script: |
        rustup component add clippy
        cargo clippy --version
      displayName: rustup component add clippy

    - script: cargo clippy --all --all-features
      displayName: cargo clippy --all --all-features
