[package]
name = "const_fn_test_suite"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
publish = false

[dev-dependencies]
const_fn = { path = ".." }
rustversion = "1.0"
