[package]
name = "const_fn_test_suite"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
publish = false

[dependencies]
const_fn = { path = ".." }

[features]
min_const_fn = []
const_unstable = ["min_const_fn"]
build_script = []
